### PR TITLE
Initial 7Z support

### PR DESCRIPTION
**Pull request by hummeltech**
Addresses #3

Also fixed issue with negative "unable to process" counts
* Caused by ability for archive files to contain multiple files

### CODE REVIEW

**Comment by vaartis** [comment]
Should probably also add `py7zr` to `requirements.txt` and/or check if it's available before using it (it will throw an ImportError if it's not available when importing), since this seems like an optional feature.

**Review by moonburnt — CHANGES_REQUESTED** [review]
thank you so much for contributing! 
Just like @vaartis has said, there should probably be some check if py7zr is installed, in order to perform related procedures. Aside from that - very nice pr.

**Comment by hummeltech** [comment]
Good idea, I updated the `requirements.txt`. Let me know if that works as a solution for you.

**Comment by moonburnt** [comment]
that would do, merged. Thanks!

**Pull request merged**
